// AUTO-GENERATED by scripts/build-lab-content.mjs — do not edit by hand.
// Regenerate: `npm run build:lab`
// Source:     ansible/inventory/hosts.yml
// Generated:  2026-04-22T02:44:59.433Z

export interface LabHost {
  readonly hostname: string;
  readonly address: string | null;
}

export interface LabHostGroup {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly hosts: readonly LabHost[];
}

export const LAB_HOST_GROUPS: readonly LabHostGroup[] = [
  {
    "id": "arr",
    "label": "Media VM",
    "description": "Media library automation — *arr suite on a dedicated VM.",
    "hosts": [
      {
        "hostname": "arr-vm",
        "address": "10.0.60.42"
      }
    ]
  },
  {
    "id": "dns",
    "label": "DNS node",
    "description": "Technitium DNS nodes — anycast-style via keepalived.",
    "hosts": [
      {
        "hostname": "dns-n2",
        "address": "10.0.60.18"
      },
      {
        "hostname": "dns-n3",
        "address": "10.0.60.20"
      }
    ]
  },
  {
    "id": "lgtm",
    "label": "Observability VM",
    "description": "Self-hosted Loki + Grafana + Tempo + Mimir stack.",
    "hosts": [
      {
        "hostname": "lgtm-vm",
        "address": "10.0.60.160"
      }
    ]
  },
  {
    "id": "nas",
    "label": "NAS",
    "description": "ZFS storage with Cloud Sync + RSync for 3-2-1 backup.",
    "hosts": [
      {
        "hostname": "cm-nas",
        "address": "10.0.60.24"
      },
      {
        "hostname": "jb-nas",
        "address": "10.0.60.22"
      }
    ]
  },
  {
    "id": "proxmox",
    "label": "Proxmox host",
    "description": "Hypervisor hosts running most VM-backed clusters.",
    "hosts": [
      {
        "hostname": "bd-n1",
        "address": "10.0.1.24"
      },
      {
        "hostname": "bd-n2",
        "address": "10.0.1.26"
      },
      {
        "hostname": "hx90",
        "address": "10.0.1.22"
      }
    ]
  },
  {
    "id": "raspbian",
    "label": "Raspberry Pi",
    "description": "Low-power utility nodes — DNS primary and edge load balancer.",
    "hosts": [
      {
        "hostname": "rpi-n1",
        "address": "10.0.60.16"
      },
      {
        "hostname": "rpi-n2",
        "address": "10.0.60.136"
      }
    ]
  },
  {
    "id": "wings",
    "label": "Game server node",
    "description": "Pelican game-server control plane on the DMZ VLAN.",
    "hosts": [
      {
        "hostname": "wings-n1",
        "address": "10.0.80.16"
      },
      {
        "hostname": "wings-n2",
        "address": "10.0.80.18"
      }
    ]
  }
] as const;

export const LAB_HOST_COUNT = 13;
