// AUTO-GENERATED by scripts/build-lab-content.mjs — do not edit by hand.
// Regenerate: `npm run build:lab`
// Source:     ansible/inventory/hosts.yml
// Generated:  2026-04-23T02:50:05.274Z

export interface LabHost {
  readonly hostname: string;
}

export interface LabHostGroup {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly hosts: readonly LabHost[];
}

export const LAB_HOST_GROUPS: readonly LabHostGroup[] = [
  {
    "id": "arr",
    "label": "Media VM",
    "description": "Media library automation — *arr suite on a dedicated VM.",
    "hosts": [
      {
        "hostname": "arr-vm"
      }
    ]
  },
  {
    "id": "dns",
    "label": "DNS node",
    "description": "Technitium DNS nodes — anycast-style via keepalived.",
    "hosts": [
      {
        "hostname": "dns-n2"
      },
      {
        "hostname": "dns-n3"
      }
    ]
  },
  {
    "id": "lgtm",
    "label": "Observability VM",
    "description": "Self-hosted Loki + Grafana + Tempo + Mimir stack.",
    "hosts": [
      {
        "hostname": "lgtm-vm"
      }
    ]
  },
  {
    "id": "nas",
    "label": "NAS",
    "description": "ZFS storage with Cloud Sync + RSync for 3-2-1 backup.",
    "hosts": [
      {
        "hostname": "cm-nas"
      },
      {
        "hostname": "jb-nas"
      }
    ]
  },
  {
    "id": "proxmox",
    "label": "Proxmox host",
    "description": "Hypervisor hosts running most VM-backed clusters.",
    "hosts": [
      {
        "hostname": "bd-n1"
      },
      {
        "hostname": "bd-n2"
      },
      {
        "hostname": "hx90"
      }
    ]
  },
  {
    "id": "raspbian",
    "label": "Raspberry Pi",
    "description": "Low-power utility nodes — DNS primary and edge load balancer.",
    "hosts": [
      {
        "hostname": "rpi-n1"
      },
      {
        "hostname": "rpi-n2"
      }
    ]
  },
  {
    "id": "wings",
    "label": "Game server node",
    "description": "Pelican game-server control plane on the DMZ VLAN.",
    "hosts": [
      {
        "hostname": "wings-n1"
      },
      {
        "hostname": "wings-n2"
      }
    ]
  }
] as const;

export const LAB_HOST_COUNT = 13;
