{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := .Chart.Name -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kian-coffee.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressRoute.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end}}
  {{- if .Values.ingressRoute.tls }}
  tls:
    secretName: {{ .Values.ingressRoute.tls.secretName }}
  {{- end }}
  routes:
    {{- range .Values.ingressRoute.hosts }}
    - match: Host(`{{ .host }}`)
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
    {{- end }}
{{- end }}
