apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  namespace: coffee-kian
spec:
  type: LoadBalancer
  selector:
    app: "{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
